package functions
import base.*
import base.context.ReferenceTo
import functions.groups.arithmetic.*
import functions.groups.branch.*
import functions.groups.dataMovement.*
import functions.groups.logical.*
import functions.groups.shift.*
import functions.groups.stack.*
import hardware.*
import jdk.nashorn.internal.ir.Flags
//Summer19
//You have to kickstart the module first
var reg = RegisterFile()
var flags = reg.flags
var memory = Memory(0)

fun initFunctionsLibrary(r: RegisterFile, m: Memory) {
    reg = r
    memory = m
}

val functionMap: Map<Int, (Base8, BaseN) -> Boolean> = mapOf(
        /*ACI 8-bit*/   0xCE to ::iACI,
        /*ADC A*/       0x8F to ::iADC,
        /*ADC B*/       0x88 to ::iADC,
        /*ADC C*/       0x89 to ::iADC,
        /*ADC D*/       0x8A to ::iADC,
        /*ADC E*/       0x8B to ::iADC,
        /*ADC H*/       0x8C to ::iADC,
        /*ADC L*/       0x8D to ::iADC,
        /*ADC M*/       0x8E to ::iADC,
        /*ADD A*/       0x87 to ::iADD,
        /*ADD B*/       0x80 to ::iADD,
        /*ADD C*/       0x81 to ::iADD,
        /*ADD D*/       0x82 to ::iADD,
        /*ADD E*/       0x83 to ::iADD,
        /*ADD H*/       0x84 to ::iADD,
        /*ADD L*/       0x85 to ::iADD,
        /*ADD M*/       0x86 to ::iADD,
        /*ADI 8-bit*/   0xC6 to ::iADI,
        /*ANA A*/       0xA7 to ::iANA,
        /*ANA B*/       0xA0 to ::iANA,
        /*ANA C*/       0xA1 to ::iANA,
        /*ANA D*/       0xA2 to ::iANA,
        /*ANA E*/       0xA3 to ::iANA,
        /*ANA H*/       0xA4 to ::iANA,
        /*ANA L*/       0xA5 to ::iANA,
        /*ANA M*/       0xA6 to ::iANA,
        /*ANI 8-bit*/   0xE6 to ::iANI,
        /*CALL 16-bit*/ 0xCD to ::iCALLX,
        /*CC 16-bit*/   0xDC to ::iCALLX,
        /*CM 16-bit*/   0xFC to ::iCALLX,
        /*CMA*/         0x2F to ::iCMA,
        /*CMC*/         0x3F to ::iCMC,
        /*CMP A*/       0xBF to ::iCMP,
        /*CMP B*/       0xB8 to ::iCMP,
        /*CMP C*/       0xB9 to ::iCMP,
        /*CMP D*/       0xBA to ::iCMP,
        /*CMP E*/       0xBB to ::iCMP,
        /*CMP H*/       0xBC to ::iCMP,
        /*CMP L*/       0xBD to ::iCMP,
        /*CMP M*/       0xBE to ::iCMP,
        /*CNC 16-bit*/  0xD4 to ::iCALLX,
        /*CNZ 16-bit*/  0xC4 to ::iCALLX,
        /*CP 16-bit*/   0xF4 to ::iCALLX,
        /*CPE 16-bit*/  0xEC to ::iCALLX,
        /*CPI 8-bit*/   0xFE to ::iCMI,
        /*CPO 16-bit*/  0xE4 to ::iCALLX,
        /*CZ 16-bit*/   0xCC to ::iCALLX,
        /*DAA*/         0x27 to { instr, arg -> fDecimaladjust(flags, RegisterReference(reg.a)) },
        /*DAD B*/       0x09 to ::dummy,
        /*DAD D*/       0x19 to ::dummy,
        /*DAD H*/       0x29 to ::dummy,
        /*DAD SP*/      0x39 to ::dummy,
        /*DCR A*/       0x3D to ::dummy,
        /*DCR B*/       0x05 to ::dummy,
        /*DCR C*/       0x0D to ::dummy,
        /*DCR D*/       0x15 to ::dummy,
        /*DCR E*/       0x1D to ::dummy,
        /*DCR H*/       0x25 to ::dummy,
        /*DCR L*/       0x2D to ::dummy,
        /*DCR M*/       0x35 to ::dummy,
        /*DCX B*/       0x0B to ::dummy,
        /*DCX D*/       0x1B to ::dummy,
        /*DCX H*/       0x2B to ::dummy,
        /*DCX SP*/      0x3B to ::dummy,
        /*DI*/          0xF3 to ::dummy,
        /*EI*/          0xFB to ::dummy,
        /*HLT*/         0x76 to ::dummy,
        /*IN 8-Bit*/    0xDB to ::dummy,
        /*INR A*/       0x3C to ::dummy,
        /*INR B*/       0x04 to ::dummy,
        /*INR C*/       0x0C to ::dummy,
        /*INR D*/       0x14 to ::dummy,
        /*INR E*/       0x1C to ::dummy,
        /*INR H*/       0x24 to ::dummy,
        /*INR L*/       0x2C to ::dummy,
        /*INR M*/       0x34 to ::dummy,
        /*INX B*/       0x03 to ::dummy,
        /*INX D*/       0x13 to ::dummy,
        /*INX H*/       0x23 to ::dummy,
        /*INX SP*/      0x33 to ::dummy,
        /*JC 16-bit*/   0xDA to ::dummy,
        /*JM 16-bit*/   0xFA to ::dummy,
        /*JMP 16-bit*/  0xC3 to ::dummy,
        /*JNC 16-bit*/  0xD2 to ::dummy,
        /*JNZ 16-bit*/  0xC2 to ::dummy,
        /*JP 16-bit*/   0xF2 to ::dummy,
        /*JPE 16-bit*/  0xEA to ::dummy,
        /*JPO 16-bit*/  0xE2 to ::dummy,
        /*JZ 16-bit*/   0xCA to ::dummy,
        /*LDA 16-bit*/  0x3A to ::dummy,
        /*LDAX B*/      0x0A to ::dummy,
        /*LDAX D*/      0x1A to ::dummy,
        /*LHLD 16-bit*/ 0x2A to ::dummy,
        /*LXI B 16-bit*/0x01 to ::iLXI,
        /*LXI D*/       0x11 to ::iLXI,
        /*LXI H 16-bit*/0x21 to ::iLXI,
        /*LXI SP 16-bit*/0x31 to ::iLXI,
        /*MOV A A*/     0x7F to ::dummy,
        /*MOV A B*/     0x78 to ::dummy,
        /*MOV A C*/     0x79 to ::dummy,
        /*MOV A D*/     0x7A to ::dummy,
        /*MOV A E*/     0x7B to ::dummy,
        /*MOV A H*/     0x7C to ::dummy,
        /*MOV A L*/     0x7D to ::dummy,
        /*MOV A M*/     0x7E to ::dummy,
        /*MOV B A*/     0x47 to ::dummy,
        /*MOV B B*/     0x40 to ::dummy,
        /*MOV B C*/     0x41 to ::dummy,
        /*MOV B D*/     0x42 to ::dummy,
        /*MOV B E*/     0x43 to ::dummy,
        /*MOV B H*/     0x44 to ::dummy,
        /*MOV B L*/     0x45 to ::dummy,
        /*MOV B M*/     0x46 to ::dummy,
        /*MOV C A*/     0x4F to ::dummy,
        /*MOV C B*/     0x48 to ::dummy,
        /*MOV C C*/     0x49 to ::dummy,
        /*MOV C D*/     0x4A to ::dummy,
        /*MOV C E*/     0x4B to ::dummy,
        /*MOV C H*/     0x4C to ::dummy,
        /*MOV C L*/     0x4D to ::dummy,
        /*MOV C M*/     0x4E to ::dummy,
        /*MOV D A*/     0x57 to ::dummy,
        /*MOV D B*/     0x50 to ::dummy,
        /*MOV D C*/     0x51 to ::dummy,
        /*MOV D D*/     0x52 to ::dummy,
        /*MOV D E*/     0x53 to ::dummy,
        /*MOV D H*/     0x54 to ::dummy,
        /*MOV D L*/     0x55 to ::dummy,
        /*MOV D M*/     0x56 to ::dummy,
        /*MOV E A*/     0x5F to ::dummy,
        /*MOV E B*/     0x58 to ::dummy,
        /*MOV E C*/     0x59 to ::dummy,
        /*MOV E D*/     0x5A to ::dummy,
        /*MOV E E*/     0x5B to ::dummy,
        /*MOV E H*/     0x5C to ::dummy,
        /*MOV E L*/     0x5D to ::dummy,
        /*MOV E M*/     0x5E to ::dummy,
        /*MOV H A*/     0x67 to ::dummy,
        /*MOV H B*/     0x60 to ::dummy,
        /*MOV H C*/     0x61 to ::dummy,
        /*MOV H D*/     0x62 to ::dummy,
        /*MOV H E*/     0x63 to ::dummy,
        /*MOV H H*/     0x64 to ::dummy,
        /*MOV H L*/     0x65 to ::dummy,
        /*MOV H M*/     0x66 to ::dummy,
        /*MOV L A*/     0x6F to ::dummy,
        /*MOV L B*/     0x68 to ::dummy,
        /*MOV L C*/     0x69 to ::dummy,
        /*MOV L D*/     0x6A to ::dummy,
        /*MOV L E*/     0x6B to ::dummy,
        /*MOV L H*/     0x6C to ::dummy,
        /*MOV L L*/     0x6D to ::dummy,
        /*MOV L M*/     0x6E to ::dummy,
        /*MOV M A*/     0x77 to ::dummy,
        /*MOV M B*/     0x70 to ::dummy,
        /*MOV M C*/     0x71 to ::dummy,
        /*MOV M D*/     0x72 to ::dummy,
        /*MOV M E*/     0x73 to ::dummy,
        /*MOV M H*/     0x74 to ::dummy,
        /*MOV M L*/     0x75 to ::dummy,
        /*MVI A 8-bit*/ 0x3E to ::dummy,
        /*MVI B 8-bit*/ 0x06 to ::dummy,
        /*MVI C 8-bit*/ 0x0E to ::dummy,
        /*MVI D 8-bit*/ 0x16 to ::dummy,
        /*MVI E 8-bit*/ 0x1E to ::dummy,
        /*MVI H 8-bit*/ 0x26 to ::dummy,
        /*MVI L 8-bit*/ 0x2E to ::dummy,
        /*MVI M 8-bit*/ 0x36 to ::dummy,
        /*NOP*/         0x00 to ::dummy,
        /*ORA A*/       0xB7 to ::dummy,
        /*ORA B*/       0xB0 to ::dummy,
        /*ORA C*/       0xB1 to ::dummy,
        /*ORA D*/       0xB2 to ::dummy,
        /*ORA E*/       0xB3 to ::dummy,
        /*ORA H*/       0xB4 to ::dummy,
        /*ORA L*/       0xB5 to ::dummy,
        /*ORA M*/       0xB6 to ::dummy,
        /*ORI 8-bit*/   0xF6 to ::dummy,
        /*OUT 8-bit*/   0xD3 to ::dummy,
        /*PCHL*/        0xE9 to ::dummy,
        /*POP B*/       0xC1 to ::dummy,
        /*POP D*/       0xD1 to ::dummy,
        /*POP H*/       0xE1 to ::dummy,
        /*POP PSW*/     0xF1 to ::dummy,
        /*PUSH B*/      0xC5 to ::dummy,
        /*PUSH D*/      0xD5 to ::dummy,
        /*PUSH H*/      0xE5 to ::dummy,
        /*PUSH PSW*/    0xF5 to ::dummy,
        /*RAL*/         0x17 to ::dummy,
        /*RAR*/         0x1F to ::dummy,
        /*RC*/          0xD8 to ::dummy,
        /*RET*/         0xC9 to ::dummy,
        /*RIM*/         0x20 to ::dummy,
        /*RLC*/         0x07 to ::dummy,
        /*RM*/          0xF8 to ::dummy,
        /*RNC*/         0xD0 to ::dummy,
        /*RNZ*/         0xC0 to ::dummy,
        /*RP*/          0xF0 to ::dummy,
        /*RPE*/         0xE8 to ::dummy,
        /*RPO*/         0xE0 to ::dummy,
        /*RRC*/         0x0F to ::dummy,
        /*RST 0*/       0xC7 to ::dummy,
        /*RST 1*/       0xCF to ::dummy,
        /*RST 2*/       0xD7 to ::dummy,
        /*RST 3*/       0xDF to ::dummy,
        /*RST 4*/       0xE7 to ::dummy,
        /*RST 5*/       0xEF to ::dummy,
        /*RST 6*/       0xF7 to ::dummy,
        /*RST 7*/       0xFF to ::dummy,
        /*RZ*/          0xC8 to ::dummy,
        /*SBB A*/       0x9F to ::dummy,
        /*SBB B*/       0x98 to ::dummy,
        /*SBB C*/       0x99 to ::dummy,
        /*SBB D*/       0x9A to ::dummy,
        /*SBB E*/       0x9B to ::dummy,
        /*SBB H*/       0x9C to ::dummy,
        /*SBB L*/       0x9D to ::dummy,
        /*SBB M*/       0x9E to ::dummy,
        /*SBI 8-bit*/   0xDE to ::dummy,
        /*SHLD 16-bit*/ 0x22 to ::dummy,
        /*SIM*/         0x30 to ::dummy,
        /*SPHL*/        0xF9 to ::dummy,
        /*STA 16-bit*/  0x32 to ::dummy,
        /*STAX B*/      0x02 to ::dummy,
        /*STAX D*/      0x12 to ::dummy,
        /*STC*/         0x37 to ::dummy,
        /*SUB A*/       0x97 to ::dummy,
        /*SUB B*/       0x90 to ::dummy,
        /*SUB C*/       0x91 to ::dummy,
        /*SUB D*/       0x92 to ::dummy,
        /*SUB E*/       0x93 to ::dummy,
        /*SUB H*/       0x94 to ::dummy,
        /*SUB L*/       0x95 to ::dummy,
        /*SUB M*/       0x96 to ::dummy,
        /*SUI 8-bit*/   0xD6 to ::dummy,
        /*XCHG*/        0xEB to ::dummy,
        /*XRA A*/       0xAF to ::dummy,
        /*XRA B*/       0xA8 to ::dummy,
        /*XRA C*/       0xA9 to ::dummy,
        /*XRA D*/       0xAA to ::dummy,
        /*XRA E*/       0xAB to ::dummy,
        /*XRA H*/       0xAC to ::dummy,
        /*XRA L*/       0xAD to ::dummy,
        /*XRA M*/       0xAE to ::dummy,
        /*XRI 8-bit*/   0xEE to ::dummy,
        /*XTHL*/        0xE3 to ::dummy
)